export const CREATE_CHAT_REQUEST = "CREATE_CHAT_REQUEST";
export const CREATE_CHAT_SUCCESS = "CREATE_CHAT_SUCCESS";
export const CREATE_CHAT_FAIL = "CREATE_CHAT_FAIL";
export const CREATE_CHAT_RESET = "CREATE_CHAT_RESET";

export const CREATE_GROUP_CHAT_REQUEST = "CREATE_GROUP_CHAT_REQUEST";
export const CREATE_GROUP_CHAT_SUCCESS = "CREATE_GROUP_CHAT_SUCCESS";
export const CREATE_GROUP_CHAT_FAIL = "CREATE_GROUP_CHAT_FAIL";
export const CREATE_GROUP_CHAT_RESET = "CREATE_GROUP_CHAT_RESET";

export const LEAVE_GROUP_CHAT_REQUEST = "LEAVE_GROUP_CHAT_REQUEST";
export const LEAVE_GROUP_CHAT_SUCCESS = "LEAVE_GROUP_CHAT_SUCCESS";
export const LEAVE_GROUP_CHAT_FAIL = "LEAVE_GROUP_CHAT_FAIL";
export const LEAVE_GROUP_CHAT_RESET = "LEAVE_GROUP_CHAT_RESET";

export const REMOVE_USER_FROM_GROUP_REQUEST = "REMOVE_USER_FROM_GROUP_REQUEST";
export const REMOVE_USER_FROM_GROUP_SUCCESS = "REMOVE_USER_FROM_GROUP_SUCCESS";
export const REMOVE_USER_FROM_GROUP_FAIL = "REMOVE_USER_FROM_GROUP_FAIL";
export const REMOVE_USER_FROM_GROUP_RESET = "REMOVE_USER_FROM_GROUP_RESET";

export const ADD_USER_TO_GROUP_REQUEST = "ADD_USER_TO_GROUP_REQUEST";
export const ADD_USER_TO_GROUP_SUCCESS = "ADD_USER_TO_GROUP_SUCCESS";
export const ADD_USER_TO_GROUP_FAIL = "ADD_USER_TO_GROUP_FAIL";
export const ADD_USER_TO_GROUP_RESET = "ADD_USER_TO_GROUP_RESET";

export const UPDATE_GROUP_NAME_REQUEST = "UPDATE_GROUP_NAME_REQUEST";
export const UPDATE_GROUP_NAME_SUCCESS = "UPDATE_GROUP_NAME_SUCCESS";
export const UPDATE_GROUP_NAME_FAIL = "UPDATE_GROUP_NAME_FAIL";
export const UPDATE_GROUP_NAME_RESET = "UPDATE_GROUP_NAME_RESET";

export const FETCH_CHAT_REQUEST = "FETCH_CHAT_REQUEST";
export const FETCH_CHAT_SUCCESS = "FETCH_CHAT_SUCCESS";
export const FETCH_CHAT_FAIL = "FETCH_CHAT_FAIL";
export const FETCH_CHAT_RESET = "FETCH_CHAT_RESET";

export const SET_SELECTED_CHAT = "SET_SELECTED_CHAT";
