export const SEND_MESSAGE_REQUEST_IN_SINGLE_CHAT =
  "SEND_MESSAGE_REQUEST_IN_SINGLE_CHAT";
export const SEND_MESSAGE_SUCCESS_IN_SINGLE_CHAT =
  "SEND_MESSAGE_SUCCESS_IN_SINGLE_CHAT";
export const SEND_MESSAGE_FAIL_IN_SINGLE_CHAT =
  "SEND_MESSAGE_FAIL_IN_SINGLE_CHAT";
export const SEND_MESSAGE_RESET_IN_SINGLE_CHAT =
  "SEND_MESSAGE_RESET_IN_SINGLE_CHAT";

export const FETCH_MESSAGES_IN_SINGLE_CHAT_REQUEST =
  "FETCH_MESSAGES_IN_SINGLE_CHAT_REQUEST";
export const FETCH_MESSAGES_IN_SINGLE_CHAT_SUCCESS =
  "FETCH_MESSAGES_IN_SINGLE_CHAT_SUCCESS";
export const FETCH_MESSAGES_IN_SINGLE_CHAT_UPDATE =
  "FETCH_MESSAGES_IN_SINGLE_CHAT_UPDATE";
export const FETCH_MESSAGES_IN_SINGLE_CHAT_FAIL =
  "FETCH_MESSAGES_IN_SINGLE_CHAT_FAIL";

export const ADD_NOTIFICATION = "ADD_NOTIFICATION";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION";
